// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.Comanda", b =>
                {
                    b.Property<Guid>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("FormaEntregaId")
                        .HasColumnType("int");

                    b.Property<int>("PrecioTotal")
                        .HasColumnType("int");

                    b.HasKey("ComandaId");

                    b.HasIndex("FormaEntregaId");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("Domain.Entity.ComandaMercaderia", b =>
                {
                    b.Property<int>("ComandaMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComandaMercaderiaId"));

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("ComandaMercaderiaId");

                    b.HasIndex("ComandaId");

                    b.HasIndex("MercaderiaId");

                    b.ToTable("ComandaMercaderia");
                });

            modelBuilder.Entity("Domain.Entity.FormaEntrega", b =>
                {
                    b.Property<int>("FormaEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaEntregaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FormaEntregaId");

                    b.ToTable("FormaEntrega");

                    b.HasData(
                        new
                        {
                            FormaEntregaId = 1,
                            Descripcion = "SALON"
                        },
                        new
                        {
                            FormaEntregaId = 2,
                            Descripcion = "DELIVERY"
                        },
                        new
                        {
                            FormaEntregaId = 3,
                            Descripcion = "PEDIDOS YA"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Mercaderia", b =>
                {
                    b.Property<int>("MercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MercaderiaId"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoMercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("MercaderiaId");

                    b.HasIndex("TipoMercaderiaId");

                    b.ToTable("Mercaderia");

                    b.HasData(
                        new
                        {
                            MercaderiaId = 1,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2020/12/sandwich-1580348_1280.jpg",
                            Ingredientes = " 4 rebanadas de pan de molde sin corteza,150 g. de atún natural en conserva,1/4 de cebolla roja cortada en cuadritos,2 cucharadas de mayonesa,Sal y pimienta al gusto",
                            Nombre = "SANDWICH DE ATUN",
                            Precio = 1500,
                            Preparacion = "En un bol agregamos el atún, la cebolla roja, la mayonesa, un poco de sal, un poco de pimienta y mezclamos todo muy bien hasta integrar.Agregamos relleno en las rebanadas de pan y luego le colocamos la otra rebanada encima.",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 2,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2021/01/sandwich-de-huevo.jpg",
                            Ingredientes = "1 pieza de pan baguette de unos 30 centímetros de largo,2 huevos,1/2 to mate,½ aguacate,4 lonjas de tocineta,2 lonchas de queso cheddar,Mayonesa al gusto,Sal al gusto",
                            Nombre = "SANDWICH DE HUEVO",
                            Precio = 2500,
                            Preparacion = "Abre la pieza de baguette por la mitad y caliéntala en una plancha a fuego suave.Cocina los huevos en omelette de forma tradicional, en una sartén no adherente y Fríe la tocineta en una sartén.",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 3,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2022/11/sandwich-de-salchichon.jpg",
                            Ingredientes = "1 pieza de pan fresco,2 rebanadas de queso blanco,8 lonchas de salchichón,Mayonesa al gusto,Pimienta al gusto",
                            Nombre = "SANDWICH DE SALCHICHON",
                            Precio = 3000,
                            Preparacion = "Coloque el pan en una bandeja para hornear durante 8-10 minutos. Retire el pan del horno y deje que se enfríe. Coloque el queso en rodajas , pepperoni , pimienta y mayonesa .",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 4,
                            Imagen = "https://elmundoenrecetas.s3.amazonaws.com/uploads/recipe/main_image/89/IMG_4520_1200px_.jpg",
                            Ingredientes = "300 gr. de salmón noruego ahumado,50 gr. de harina de trigo,Queso crema,Pan de cereales, 2 cucharadas de mayonesa,1/2 cucharadita de eneldo,Ralladura de limón,1/2 limón,Rúcula ",
                            Nombre = "BOCATA DE SALMON",
                            Precio = 1330,
                            Preparacion = "en un recipiente agregamos la mayonesa, el eneldo, la ralladura de limón, el jugo de limón y mezclamos tostar las rebanadas del pan,le untamos queso crema, luego a la otra rebanada le untamos la mayonesa.Agregamos el salmón, la rúcula y ya.",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 5,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2020/12/delicious-roasted-young-potatoes-with-dill-top-view-1536x1024.jpg",
                            Ingredientes = "1 kilo de papas cambray,½ cebolla entera,3 dientes de ajo,1 lata de chile chipotle,5 chiles guajillos,Sal al gusto,Pimienta al gusto,½ taza de agua,½ cucharada de achiote",
                            Nombre = "PAPAS ADOBADAS",
                            Precio = 500,
                            Preparacion = " Asa los chiles guajillo con el ajo y la cebolla entera, hirviendo los chiles por 20 minutos,Licúa todo, menos las papas,Cuela la salsa,Hierve las papas con sal por 10 minutos,Mezcla las papas con el adobo y marina por una hora, hornea por 15",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 6,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2016/06/pasta-5579058_1280.jpg",
                            Ingredientes = "2 porciones de fettuccine también le dicen fettuccini,2 cucharadas de mantequilla,½ taza de queso parmesano rallad,2 cucharadas de mantequilla,1 taza de nata,½ taza de queso parmesano rallado,2 dientes de ajo picados muy pequeño,Pimienta ",
                            Nombre = "PASTA ALFREDO",
                            Precio = 3100,
                            Preparacion = "Cocina la pasta, le agregas la mantequilla y el queso .Revuelve, agrega pimienta y listo.Caliente una sartén con aceite y fríe los ajos, agrega la mantequilla y la nata.Agrega el queso parmesano. Mezcla .Ponle la mescla a tu pasta favorita",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 7,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2021/01/pizza-4242967_1280.jpg",
                            Ingredientes = "400 gramos harina,200 ml agua tibia,2 cucharadas aceite de oliva,15 gramos levadura fresca,pizca de sal,1 taza salsa de jitomate,1 taza queso mozzarella,¼ taza queso parmesano rallado,Pepperoni o jamón al gusto",
                            Nombre = "MINI PIZZAS",
                            Precio = 2100,
                            Preparacion = "En un bowl agrega el aceite, el agua y la levadura.Mezcla y añade la harina ,sal y amasa 5 minutos .reposar tu masa una hora. haz pequeñas tortillitas circulares.Coloca salsa de jitomate, mozzarella ,parmesano y pepperoni .Hornea de15 minutos",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 8,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2023/03/sopa-de-pescado-con-arroz.jpg",
                            Ingredientes = "1/2 kg de filetes de pescado blanco merluza o lenguado,1 cebolla,2 dientes de ajo,1 pimiento rojo ,1 papa grande ,1 taza de arroz blanco,perejil fresco ,4 tazas de caldo de pescado,2 cucharadas de aceite de oliva,Sal al gusto,Pimienta negra ",
                            Nombre = "SOPA DE PESCADO CON ARROZ",
                            Precio = 1900,
                            Preparacion = "Calienta olla con aceite . Añade la cebolla, el ajo y el pimiento rojo y cocina por 5 minutos, .Añade las papas, el arroz y cocinar a fuego lento por 15 minutos. luego los filetes de pescado y cocinar 5 minutos .Añade sal y pimienta, y el perejil .",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 9,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2023/02/Mimosa-paso-3-PG_BCC200120006-300x169.jpg",
                            Ingredientes = "½ litro de champaña fría,½ litro de zumo de naranja natural,rodajas de naranja para decorar",
                            Nombre = "MIMOSA",
                            Precio = 900,
                            Preparacion = "Debes usar una copa larga, sirve la mitad de champaña.Completa la copa con jugo de naranja, es decir, son partes iguales de champaña y de jugo.Decora con frambuesas congeladas y una rodaja de naranja. Disfruta.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 10,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2023/02/coctel-con-champagne-paso-4-PG_BCC200120010-300x169.jpg",
                            Ingredientes = "3 cdas. de puré de fresa fresco,½ cdta. de jugo de limón,Champaña,Fresa cortada en rodajas para decorar,Corteza de limón",
                            Nombre = "COCTEL DE CHAMPAÑA, FRESAS Y LIMÓN",
                            Precio = 900,
                            Preparacion = "Mezcla el puré de fresas con el limón.En una copa larga añade la mezcla .Rellena el resto de la copa con champaña.Decora con una rebanada de fresa y con corteza de limón. Disfruta.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 11,
                            Imagen = "https://cdn7.kiwilimon.com/recetaimagen/12746/18280.jpg",
                            Ingredientes = "2 onzas de tequila,1 limón,1/2 cda de sal (para escarchar el vaso),1 caso de refresco de toronja,Hielos en cubos",
                            Nombre = "PALOMA",
                            Precio = 900,
                            Preparacion = "Toma tu vaso, lo humedecerás col limón en el borde y los vas a escarchar con la sal.Ahora, en la coctelera agregarás el hilo , el tequila, una pizca de sal y un poco de limón,mezclar y servirás en el vaso con la toronja.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 12,
                            Imagen = "https://www.recetasderechupete.com/wp-content/uploads/2022/11/Tequila-Sunrise.jpg",
                            Ingredientes = "3 onzas de tequila,4 naranjas,3 onzas de granadina,2 rodajas de limón,1 cereza",
                            Nombre = "SUNRISE",
                            Precio = 1000,
                            Preparacion = "En una coctelera, añadirás el hielo, el tequila y el jugo de naranja. Mezcla y añadirás la granadina y un poco de limón.añadir la mezcla del resto de los ingredientes para formar tu cóctel.Decora con las rodajas de limón y la cereza.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 13,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2023/04/Martini-de-mazapan-PG_MDM180520002.jpg",
                            Ingredientes = "1 mazapán,3 hielos,4 oz de leche evaporada,¾ oz de licor de avellana,½ oz de licor de café,1 ½ oz de vodka,Azúcar con canela,Chocolate líquido",
                            Nombre = "MARTINI DE MAZAPAN",
                            Precio = 800,
                            Preparacion = "Escarcha la copa con chocolate líquido.Pasa la copa por la mezcla de azúcar con canela.Coloca hielos, la leche , el licor de avellana, 1 pieza de mazapán, licor de café y vodka.Agita.Sirve en la copa y decora con chocolate líquido. ",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 14,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2022/08/Choripan-con-chimichurri-PG_CHCCH191021_01.jpg",
                            Ingredientes = "1 libra chorizo argentino,2 baguettes,¼ taza agua,6 cdas. vinagre de vino tinto,6 dientes de ajo,1 hoja de laurel,½ cdta. hojuelas de chile seco,1 cda. orégano,1 cda. pimienta,½ taza aceite de oliva,1 taza perejil rizado",
                            Nombre = "CHORIPAN CON CHIMICHURRI",
                            Precio = 500,
                            Preparacion = "En un bowl agrega el agua, el vinagre, el ajo, el laurel el chile seco,perejil, el orégano, la pimienta y aceite . Mezcla bien.Para el choripán, chorizos en el grill durante 2 minutos.Corta los panes, rellena con el chorizo y chimichurri ",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 15,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2022/08/brocheta-de-carne-con-verduras.jpeg",
                            Ingredientes = "600 gr de carne (cortada para brochetas)1 pimiento rojo,1 cebolla morada,2 calabacitas,Sal, pimienta y ajo en polvo al gusto,Salsa sazonadora o barbecue,2 cdas de cilantro fresco picado.Aceite de oliva",
                            Nombre = "BROCHETAS DE CARNE CON VERDURAS",
                            Precio = 700,
                            Preparacion = "Añade la carne en un bol, y agrega el jugo de limón, el cilantro picado, el ajo en polvo, la sal y la pimienta. Mezcla .sazonada tu carne,dejarás marinar. coloca un trozo de carne, luego las verduras en el palillo.en sartén con aceite y Cocina",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 16,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2022/08/Chuzos-ecuatorianos-shutterstock_2160614305.jpg",
                            Ingredientes = "1 kg. lomo de asado limpiozos,3 cdas. aceite con achiote,4 dientes de ajo rallados,1 cda. comino molido,1 cdta. pimienta molida,½ cda. sal,Palitos de madera para chuzos Humedecidos 40 minutos antes de armarlos",
                            Nombre = "CHUZOS ECUATORIANOS",
                            Precio = 800,
                            Preparacion = "Dentro de un bol añade el ajo, el comino, la sal, el aceite y la pimienta. Mezcla.Agrega la carne y deja marinar por 2 horas.Toma la carne, y ve insertándola en el palito, Sobre la parrilla coloca los chuzos y deja cocinar por 5 minutos ",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 17,
                            Imagen = "https://elmundoenrecetas.s3.amazonaws.com/uploads/recipe/main_image/63/IMG-3268_1200_px__2_.jpg",
                            Ingredientes = "24 alitas de pollo, 150 ml. de salsa de tomate natural,3 cucharadas de salsa de soja,2 cucharadas de vinagre de arroz, 1 cucharada de papelón o panela molida,1 cucharada de sriracha,Semillas de ajonjolí,Sal al gusto,Pimienta al gusto",
                            Nombre = "ALITAS DE POLLO ESTILO COREANO",
                            Precio = 1200,
                            Preparacion = "En una olla a fuego con tomate natural, la salsa de soja, el vinagre de arroz, el papelón o panela molida, la sriracha y mezcla. agraga un poco de sal y pimienta, y cocinar por 25 minutos.agrega salsa oriental y cocinar por 10 minutos ",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 18,
                            Imagen = "https://elmundoenrecetas.s3.amazonaws.com/uploads/recipe/main_image/491/arroz_con_leche_y_chocolate.webp",
                            Ingredientes = "100 g. de arroz arborio o arroz bomba,900 ml. de leche entera,1 rama de canela,70 g. de azúcar,1 cucharada de vainilla, 70 g. de chocolate puro,Chocolate rallado a gusto para decorar",
                            Nombre = "ARROZ CON LECHE Y CHOCOLATE",
                            Precio = 1800,
                            Preparacion = "En un cazo, agregamos la leche, la rama de canela, la vainilla y mezclamos, agregamos el arroz y cocinar por 45 minutos .Agregamos el azúcar, removemos y dejamos cocinar por 10 minutos, agregamos el chocolate fundido a nuestro arroz con leche y mescla.",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 19,
                            Imagen = "https://elmundoenrecetas.s3.amazonaws.com/uploads/recipe/main_image/191/IMG_8913-1200.jpg",
                            Ingredientes = "250 g. de ricota,150 g. de harina,60 g. de azúcar,1 huevo,Ralladura de limón,6 g. de polvo de hornear,Azúcar Glass,Leche condensada,Aceite para freír",
                            Nombre = "CASTAÑAS DE RICOTA",
                            Precio = 900,
                            Preparacion = "En un recipiente colocar la ricota, el huevo, el azúcar, y mezclamos todo, agregamos la ralladura de limón, la harina y mezclamos . formar las bolitas, las freímos hasta dorar, las sacamos y Econ el agregamos azúcar glass y leche condensada ",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 20,
                            Imagen = "https://elmundoenrecetas.s3.amazonaws.com/uploads/recipe/main_image/261/IMG_1675-1280.jpg",
                            Ingredientes = "2 plátanos cortados en rodajas,2 huevos,150 g. de azúcar,225 g. de harina de trigo todo uso,1 y 1/2 cucharadita de levadura química o polvo de hornear,80 g. de chocolate,1 cucharadita de canela en polvo,100 ml. de aceite vegetal",
                            Nombre = "BIZCOCHO DE PLÁTANO Y CHOCOLATE",
                            Precio = 850,
                            Preparacion = "trituramos nuestro plátano y en un recipiente colocar el aceite, el azúcar y con la ayuda de unas varillas, mezclar, agregamos los huevos y el plátano mezclar.agregamos la levadura, la canela en polvo, el chocolate  y horno por 45 minutos",
                            TipoMercaderiaId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entity.TipoMercaderia", b =>
                {
                    b.Property<int>("TipoMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMercaderiaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoMercaderiaId");

                    b.ToTable("TipoMercaderia");

                    b.HasData(
                        new
                        {
                            TipoMercaderiaId = 1,
                            Descripcion = "ENTRADA"
                        },
                        new
                        {
                            TipoMercaderiaId = 2,
                            Descripcion = "MINUTAS"
                        },
                        new
                        {
                            TipoMercaderiaId = 3,
                            Descripcion = "PASTAS"
                        },
                        new
                        {
                            TipoMercaderiaId = 4,
                            Descripcion = "PARRILLA"
                        },
                        new
                        {
                            TipoMercaderiaId = 5,
                            Descripcion = "Pizzas"
                        },
                        new
                        {
                            TipoMercaderiaId = 6,
                            Descripcion = "SANDWICH"
                        },
                        new
                        {
                            TipoMercaderiaId = 7,
                            Descripcion = "ENSALADAS"
                        },
                        new
                        {
                            TipoMercaderiaId = 8,
                            Descripcion = "BEBIDAS"
                        },
                        new
                        {
                            TipoMercaderiaId = 9,
                            Descripcion = "CERVEZA ARTESANAL"
                        },
                        new
                        {
                            TipoMercaderiaId = 10,
                            Descripcion = "POSTRES"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Comanda", b =>
                {
                    b.HasOne("Domain.Entity.FormaEntrega", "FKFormaEntrega")
                        .WithMany("LsComanda")
                        .HasForeignKey("FormaEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FKFormaEntrega");
                });

            modelBuilder.Entity("Domain.Entity.ComandaMercaderia", b =>
                {
                    b.HasOne("Domain.Entity.Comanda", "FKComanda")
                        .WithMany("LsComandaMercaderia")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Mercaderia", "FKMercaderia")
                        .WithMany("LsComandaMercaderia")
                        .HasForeignKey("MercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FKComanda");

                    b.Navigation("FKMercaderia");
                });

            modelBuilder.Entity("Domain.Entity.Mercaderia", b =>
                {
                    b.HasOne("Domain.Entity.TipoMercaderia", "FKTipoMercaderia")
                        .WithMany("LsMercaderia")
                        .HasForeignKey("TipoMercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FKTipoMercaderia");
                });

            modelBuilder.Entity("Domain.Entity.Comanda", b =>
                {
                    b.Navigation("LsComandaMercaderia");
                });

            modelBuilder.Entity("Domain.Entity.FormaEntrega", b =>
                {
                    b.Navigation("LsComanda");
                });

            modelBuilder.Entity("Domain.Entity.Mercaderia", b =>
                {
                    b.Navigation("LsComandaMercaderia");
                });

            modelBuilder.Entity("Domain.Entity.TipoMercaderia", b =>
                {
                    b.Navigation("LsMercaderia");
                });
#pragma warning restore 612, 618
        }
    }
}
